export const DESCRIPTIONS = {
  names: [
    'Neo',
    'Avanza',
    'Plus',
    'Smart',
    'Futuro',
    'Flex',
    'Libre',
    'Conecta',
    'Progreso',
    'Vital',
    'Clásica',
    'Elite',
    'Prime',
    'Infinity',
    'Platinum',
    'Jovenes',
    'Pro',
    'Capital',
    'Business',
    'Elite',
    'Premium',
    'Activa',
  ],
  audiences: ['NATURAL', 'BUSINESS', 'ALL'],
  rateTypes: ['EA', 'NMV', 'EM'],
  headlines: [
    'Tu dinero, más fácil y seguro',
    'Financia tus metas hoy',
    'Beneficios para tu día a día',
    'Crece con una solución flexible',
    'Ahorra e invierte con confianza',
  ],
  generalInfos: [
    'Producto financiero con disponibilidad digital diseñado para ofrecer una experiencia segura, flexible y adaptada a distintos perfiles de usuario. Permite realizar operaciones básicas y avanzadas desde canales digitales, brindando control total sobre movimientos, consultas y configuraciones. Las condiciones están sujetas a validación interna, políticas de la entidad y cumplimiento de requisitos regulatorios vigentes.',
    'Esta solución bancaria integra acceso a través de aplicaciones y plataformas digitales que facilitan la gestión diaria de tus productos financieros. Ofrece herramientas para monitorear transacciones, establecer límites y recibir notificaciones en tiempo real. Su disponibilidad y condiciones pueden variar según el perfil del cliente, evaluación de riesgo y lineamientos internos establecidos por la institución.',
    'Pensado para usuarios que buscan autonomía y eficiencia en la administración de sus finanzas, este producto permite realizar operaciones desde cualquier lugar mediante canales digitales seguros. Incluye opciones de consulta, control y seguimiento de movimientos, además de soporte en línea. Todas las condiciones están sujetas a validación, políticas internas y cumplimiento de normas regulatorias.',
    'Solución financiera orientada a la autogestión, que brinda acceso a herramientas digitales para administrar tus recursos de forma clara y segura. Permite visualizar saldos, movimientos y notificaciones relevantes, así como configurar preferencias según tus necesidades. La activación y uso del producto dependen de la validación del perfil del cliente y los criterios internos de la entidad.',
    'Producto diseñado para facilitar el manejo de tus finanzas a través de plataformas digitales intuitivas y seguras. Ofrece funcionalidades para consultar información, realizar movimientos y recibir soporte por canales en línea. Las condiciones de acceso, límites y beneficios están sujetas a evaluación del perfil del usuario, políticas internas y normativas vigentes aplicables.',
  ],
  requirements: [
    'Cédula vigente y validación de identidad.',
    'Persona mayor de 18 años.',
    'Documento, correo y número de celular activos.',
    'Historial sujeto a evaluación.',
    'KYC/SARLAFT y aceptación de términos.',
    'Soportes de ingresos si aplica.',
  ],
  termPool: [
    'Rotativo',
    'Indefinido',
    '6 a 24 meses',
    '12 a 60 meses',
    '180 días',
    '360 días',
  ],
} as const;
