export const DESCRIPTIONS = {
  names: [
    'Neo',
    'Avanza',
    'Plus',
    'Smart',
    'Futuro',
    'Flex',
    'Libre',
    'Conecta',
    'Progreso',
    'Vital',
    'Clásica',
    'Elite',
    'Prime',
    'Infinity',
    'Platinum',
    'Jovenes',
    'Pro',
    'Capital',
    'Business',
    'Elite',
    'Premium',
    'Activa',
  ],
  audiences: ['NATURAL', 'BUSINESS', 'BOTH'],
  rateTypes: ['EA', 'NMV', 'EM'],
  headlines: [
    'Tu dinero, más fácil y seguro',
    'Financia tus metas hoy',
    'Beneficios para tu día a día',
    'Crece con una solución flexible',
    'Ahorra e invierte con confianza',
  ],
  generalInfos: [
    'Producto con disponibilidad digital y condiciones según perfil.',
    'Incluye acceso por app, movimientos y soporte en canales digitales.',
    'Condiciones sujetas a validación y políticas internas.',
    'Ideal para quienes buscan flexibilidad y autogestión.',
    'Solución financiera con opciones de uso y control.',
  ],
  requirements: [
    'Cédula vigente y validación de identidad.',
    'Documento, correo y número de celular activos.',
    'Historial sujeto a evaluación.',
    'KYC/SARLAFT y aceptación de términos.',
    'Soportes de ingresos si aplica.',
  ],
  termPool: [
    'Rotativo',
    'Indefinido',
    '6 a 24 meses',
    '12 a 60 meses',
    '180 días',
    '360 días',
  ],
} as const;
